version: '3'
services:
  db:
    build: ./
    # image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    volumes:
      - "${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres
    command: -c log_statement=all
    # command: -c log_statement=mod
    # command: -c log_min_duration_statement=250
    # command: -c log_statement=all -c log_min_duration_statement=250
    # command: -c log_statement=mod -c log_min_duration_statement=250
