version: '3'
services:
  db:
    build: ./
    # image: postgres:14.5-bullseye
    ports:
      - 5432:5432
    volumes:
      - "${PWD}/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    environment:
      POSTGRES_PASSWORD: postgres
